export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#be185d",
                "primary-light": "#fdf2f8",
                "rajkumari": "#D12E68",
                "rajkumari-pink": "#E35A79",
                "rajkumari-light": "#FADADD",
                "ghee": "#F3C969",
                "ghee-yellow": "#F3C969",
                "ghee-light": "#FFF8E1",
                "ghee-dark": "#d97706",
                "secondary": "#f59e0b",
                "secondary-light": "#fef3c7",
                "background-ivory": "#fdfbf7",
                "background-light": "#FCFCFA",
                "ivory": "#FFFCF9",
                "paper": "#FAFAFA",
                "stone-paper": "#F7F5F0",
                "surface": "#ffffff",
                "text-charcoal": "#334155",
                "charcoal": "#2D2A26",
                "text-muted": "#64748b",
                "ink": "#111827",
                "ink-light": "#4B5563",
                "slate-grey": "#635F59",
                "border-subtle": "#e7e5e4",
                "subtle-border": "#E8E2D2",
                "luxury-border": "#E2E0DC",
                "line": "#E5E7EB",
            },
            fontFamily: {
                "display": ["Spline Sans", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "serif": ["Playfair Display", "serif"],
                "sans": ["Inter", "sans-serif"],
            },
            borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
            boxShadow: {
                'soft': '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
                'glow': '0 0 15px rgba(190, 24, 93, 0.3)',
                'glow-pink': '0 4px 20px -5px rgba(209, 46, 88, 0.3)',
                'executive': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                'floating': '0 10px 30px -10px rgba(0, 0, 0, 0.08)',
            }
        },
    },
    plugins: [],
}
