services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    # I changed this to 5002 because your Ecommerce backend is already using port 5000!
    ports:
      - "5002:5000"
    networks:
      - infra_internal
    environment:
      PORT: 5000
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5178:5178"
    networks:
      - infra_internal
    depends_on:
      - backend

# This tells Docker to use your existing network instead of creating a new one
networks:
  infra_internal:
    external: true
